// Renders the end-to-end run as one self-contained HTML page: the install, then every scenario
// grouped by hook, each with what was expected, the verdict, and the evidence read back from the
// session. Same phosphor as the docs site: clay on near-black, JetBrains Mono throughout.

import { readFileSync } from "node:fs";

// Kept in its own file so Prettier formats it; inlined, so the page needs nothing beside it.
const STYLE = readFileSync(new URL("./report.css", import.meta.url), "utf8");
const FONT =
  "https://fonts.googleapis.com/css2?" + "family=JetBrains+Mono:wght@400;600;800&display=swap";

const HOOK_ORDER = ["RECOVERABLE", "FLAG-PROBE", "DONE-GATE"];
const HOOK_LINE = {
  RECOVERABLE: "PreToolUse · Bash · a delete git cannot give back",
  "FLAG-PROBE": "PreToolUse · Bash · --help on a script nobody read",
  "DONE-GATE": "Stop · a “done” with no test run since the last edit",
};

const esc = (value) =>
  String(value ?? "").replace(
    /[&<>"']/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c],
  );

/** @param {any} report the object e2e/run.mjs writes to report.json */
export function renderReport(report) {
  const groups = HOOK_ORDER.map((hook) => ({
    hook,
    rows: report.scenarios.filter((s) => s.hook === hook),
  })).filter((g) => g.rows.length);

  return `<title>jord0.hooks Vanilla Run</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="stylesheet" href="${FONT}">
<style>
${STYLE}</style>
<main>
  ${header(report)}

  ${installSection(report.install)}

  ${groups.map(hookSection).join("\n\n  ")}

  <footer>
    Generated by <code>e2e/run.mjs</code>. Raw sessions for every scenario are kept beside this
    page in <code>e2e/report/sessions/</code>.
  </footer>
</main>
`;
}

function header(report) {
  const total = report.scenarios.length;
  const passed = report.scenarios.filter((s) => s.pass).length;
  const allGreen = passed === total && report.install.pass;
  const install = report.install.pass ? "ok" : "failed";
  const tally = `${passed} / ${total} scenarios passed · install ${install}`;
  return `<header>
    <h1>jord0.hooks · vanilla run<span class="cursor" aria-hidden="true"></span></h1>
    <p class="lede">
      A stock Claude Code in a fresh container: the npm package, an empty home, no CLAUDE.md, no
      other hooks. The plugin was installed from its committed tree through a marketplace, and
      each scenario ran through <code>claude -p</code>. Every verdict below is read from the
      session and the disk afterwards, never from the model's own account.
    </p>
    <ul class="facts">
      <li>commit <b>${esc(report.head)}</b></li>
      <li>Claude Code <b>${esc(report.install.claudeVersion || report.version)}</b></li>
      <li>model <b>${esc(report.model)}</b></li>
      <li>ran <b>${esc(report.started)}</b></li>
    </ul>
    <div class="tally ${allGreen ? "ok" : "bad"}">${tally}</div>
  </header>`;
}

function installSection(install) {
  const dependencies = install.dependenciesInstalled
    ? esc(install.dependencyPath)
    : "not found in the plugin cache";
  const title = "the plugin installs and its dependencies arrive without any step by the user";
  return `<section class="install" aria-labelledby="install">
    <h2 id="install">
      Install <small>marketplace → claude plugin install → npm ci --ignore-scripts</small>
    </h2>
    <article class="scenario ${install.pass ? "pass" : "fail"}">
      ${row("S0", title, install.pass)}
      <p class="expect"><span>dependencies:</span> ${dependencies}</p>
      <details>
        <summary>CLI output</summary>
        <pre>${esc(`${install.marketplace}\n${install.install}`)}</pre>
      </details>
    </article>
  </section>`;
}

function hookSection({ hook, rows }) {
  return `<section aria-labelledby="h-${hook}">
    <h2 id="h-${hook}">${esc(hook)} <small>${esc(HOOK_LINE[hook])}</small></h2>
    ${rows.map(scenario).join("\n    ")}
  </section>`;
}

function scenario(s) {
  const files = Object.entries(s.exists ?? {})
    .map(([path, present]) => `${path} ${present ? "exists" : "absent"}`)
    .join(" · ");
  const meta = [
    `mode ${s.mode === "bypass" ? "bypassPermissions" : "Manual"}`,
    `${s.seconds} s`,
    `$${s.cost ?? "?"}`,
    ...(files ? [files] : []),
  ];
  const exchange = `PROMPT\n${s.prompt}\n\nFINAL REPLY\n${s.finalText}`;
  return `<article class="scenario ${s.pass ? "pass" : "fail"}">
      ${row(esc(s.id), esc(s.title), s.pass)}
      <div class="meta">${meta.map((m) => `<span>${esc(m)}</span>`).join("")}</div>
      <p class="expect"><span>expected:</span> ${esc(s.expect)}</p>
      <pre>${esc(s.evidence)}</pre>
      <details>
        <summary>prompt and final reply</summary>
        <pre>${esc(exchange)}</pre>
      </details>
    </article>`;
}

/** The first line of a card: its id, what it checks, and the verdict. */
function row(id, title, pass) {
  return (
    `<div class="row"><span class="id">${id}</span><span class="title">${title}</span>` +
    `<span class="verdict">${pass ? "PASS" : "FAIL"}</span></div>`
  );
}
